// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tQuhRfAC7zbkVhp0LV3qEq3bR8TgXUU',
    appId: '1:988927481532:web:67ccd140887676d5e7a2b9',
    messagingSenderId: '988927481532',
    projectId: 'prm393-686b8',
    authDomain: 'prm393-686b8.firebaseapp.com',
    storageBucket: 'prm393-686b8.firebasestorage.app',
    measurementId: 'G-E4G73FX7DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xc0TL0SQ518XxAKYgH6DVd25mm5xMKw',
    appId: '1:988927481532:android:9f8c412ddaf70ecce7a2b9',
    messagingSenderId: '988927481532',
    projectId: 'prm393-686b8',
    storageBucket: 'prm393-686b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuARKgDdGG07PdbU9XI7W8_uD8uoDpPu4',
    appId: '1:988927481532:ios:25c20ec2104a17e2e7a2b9',
    messagingSenderId: '988927481532',
    projectId: 'prm393-686b8',
    storageBucket: 'prm393-686b8.firebasestorage.app',
    iosClientId: '988927481532-e6e3673qm23cal1tcsqi33ppcj2erp3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vietnameseSignLanguagePlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuARKgDdGG07PdbU9XI7W8_uD8uoDpPu4',
    appId: '1:988927481532:ios:25c20ec2104a17e2e7a2b9',
    messagingSenderId: '988927481532',
    projectId: 'prm393-686b8',
    storageBucket: 'prm393-686b8.firebasestorage.app',
    iosClientId: '988927481532-e6e3673qm23cal1tcsqi33ppcj2erp3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.vietnameseSignLanguagePlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tQuhRfAC7zbkVhp0LV3qEq3bR8TgXUU',
    appId: '1:988927481532:web:d41c6835914706ffe7a2b9',
    messagingSenderId: '988927481532',
    projectId: 'prm393-686b8',
    authDomain: 'prm393-686b8.firebaseapp.com',
    storageBucket: 'prm393-686b8.firebasestorage.app',
    measurementId: 'G-T2VS73EQJ6',
  );
}
